// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3igYQjOTm8kNW1uxC07tlaHTU-gTiTU',
    appId: '1:912237378642:web:7022c5a14eac94cf3fb38b',
    messagingSenderId: '912237378642',
    projectId: 'foodorderingapp-4e968',
    authDomain: 'foodorderingapp-4e968.firebaseapp.com',
    storageBucket: 'foodorderingapp-4e968.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_bfG11mltDHCJv9TrjLVT4zxE341PsW0',
    appId: '1:912237378642:android:62b68b6423b06b133fb38b',
    messagingSenderId: '912237378642',
    projectId: 'foodorderingapp-4e968',
    storageBucket: 'foodorderingapp-4e968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxINsjH2-qIdW_hoN0Zj6n5972HhxJz4',
    appId: '1:912237378642:ios:455e118ab988cb5d3fb38b',
    messagingSenderId: '912237378642',
    projectId: 'foodorderingapp-4e968',
    storageBucket: 'foodorderingapp-4e968.firebasestorage.app',
    iosBundleId: 'com.example.miniFoodOrdering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxINsjH2-qIdW_hoN0Zj6n5972HhxJz4',
    appId: '1:912237378642:ios:455e118ab988cb5d3fb38b',
    messagingSenderId: '912237378642',
    projectId: 'foodorderingapp-4e968',
    storageBucket: 'foodorderingapp-4e968.firebasestorage.app',
    iosBundleId: 'com.example.miniFoodOrdering',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3igYQjOTm8kNW1uxC07tlaHTU-gTiTU',
    appId: '1:912237378642:web:51b111daebc4b63d3fb38b',
    messagingSenderId: '912237378642',
    projectId: 'foodorderingapp-4e968',
    authDomain: 'foodorderingapp-4e968.firebaseapp.com',
    storageBucket: 'foodorderingapp-4e968.firebasestorage.app',
  );
}
